import firebase from "firebase/app";
import { auth, db } from "../lib/firebase";

function SingIn() {
  const provider = new firebase.auth.GoogleAuthProvider();

  const singInWithGoogle = async () => {
    try {
      //get the signed user data (generated by firestore)
      const result = await auth.signInWithPopup(provider);
      const { uid, email, displayName: name } = result.user;
      //saving the user to firestore
      db.collection("users").doc(uid).set({ email, name }, { merge: true });
    } catch (error) {
      console.log("An error happened in the sing in process", error);
    }
  };

  return (
    <div>
      <button onClick={singInWithGoogle}>Sing in With Google</button>
    </div>
  );
}

export default SingIn;
