import { useContext } from "react";
import firebase from "firebase/app";
import { auth, db } from "../lib/firebase";
import { UserContext } from "../lib/UserContext";

/**
 *
 *
 *
 */
function SingIn() {
  const { user, setUser } = useContext(UserContext);

  const singInWithGoogle = async () => {
    try {
      //setting persistence
      await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);
      const provider = new firebase.auth.GoogleAuthProvider();
      //get the signed user data (generated by firestore)
      const result = await auth.signInWithPopup(provider);
      //update the state of the user in the app
      setUser(result.user);
      //saving the user to firestore
      const { uid, email, displayName: name } = result.user;
      db.collection("users").doc(uid).set({ email, name }, { merge: true });
    } catch (error) {
      console.log("An error happened in the sing in process", error);
    }
  };

  return (
    <div>
      <button onClick={singInWithGoogle}>Sing in With Google</button>
    </div>
  );
}

export default SingIn;
